version: "3.8"

services:
  api:
    build: .
    container_name: mailbox_api
    env_file: .env
    volumes:
      - ./certs:/certs:ro
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --proxy-headers
  test:
    build: .
    env_file: .env
    volumes:
      - ./certs:/certs:ro
    command: pytest -q
