version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mailbox_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # re‑export the DATABASE_URL from .env so your app can read it
      DATABASE_URL: "${DATABASE_URL}"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
