version: "3.8"

services:
  api:
    build:
      context: .
      target: runtime # <- final stage
    env_file: .env
    container_name: mailbox_api
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      retries: 3
      timeout: 5s

  test:
    build:
      context: .
      target: builder # <- stage that has pytest
    env_file: .env
    command: pytest -q
    volumes:
      - ./certs:/certs:ro
